### ISSUE TITLE
Scaffold documentation repo and Markdown rendering engine

### ISSUE THREAD

**Issue by hxlnt** [microsoft/cobalt#103]
**A good user story should be (I-N-V-E-S-T principle)**

* _Independent_ (from other user stories, allowing to realize them in any order);
* _Negotiable_ (omit details that would freeze the story);
* _Valuable_ (implementation delivers an increment of functionality, observable by and useful to users);
* _Estimable_ (developers should be able to estimate its size relative to other stories);
* _Sizable_ (implementation fits in one iteration – if it needs many to complete, it is an EPIC);
* _Testable_ (user must be able to check the conditions of satisfaction).

### Description
*As a user, I'd like a centralized location for Cobalt/Bedrock/Helium documentation in order to choose and deploy the solution best suited to my scenario.*

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] New repo should be created in Microsoft organization.
- [ ] Repo should contain rendering engine dependencies and a minimal working website testable by cloning repo and running locally (*e.g.,* `npm run my-doc-generation-tool`).

Also, here are a few points that need to be addressed:

1. Consensus should be reached on which rendering engine best addresses our need to organize documentation flexibly and with automation in mind.

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates additional work, then team should discuss promoting the user story to an epic. References: [Minimal Valuable Slices](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md), [How to Write Better Tasks](http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

Tasks:
- [ ] Create new repo in Microsoft organization.
- [ ] Select documentation rendering engine.
- [ ] Push starter site for selected documentation rendering engine.
- [ ] Confirm that site correctly renders Markdown in localhost (*e.g.,* `npm run my-doc-generation-tool` run locally).
