### ISSUE TITLE
Create documentation wireframes

### ISSUE THREAD

**Issue by hxlnt** [microsoft/cobalt#104]
### Description

*As a developer, I'd like wireframes of a multi-repo documentation site in order to guide its future development and implementation.*

All documentation will reside in a unified documentation site for the user's convenience. This documentation will be rendered from Markdown files containing custom metadata embedded in each file. Navigation (*e.g.,* link sidebars) will be generated by the values in this metadata. 

Additionally, we want to create an interactive, "choose-your-own-adventure" guide to the documentation. This may or may not be Markdown-driven, but it will direct users to documentation based on the results.

The documentation will also contain links out to GitHub samples, Slack, etc.

We plan to use [Hugo](https://gohugo.io) to render the Markdown to a static site, with hosting on GitHub pages.

### Acceptance Criteria
Reference: [Done-Done Checklist](https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Wireframes should illustrate a landing page that unifies the documentation.
- [x] Wireframes should illustrate examples of the basic types of content as described in the description above.
- [x] Wireframes should illustrate how developer-generated Markdown will feed into content rendering.
- [x] Wireframes should make a first best-guess at category types for illustrative purposes, with the understanding that these may be expanded and adapted as documentation grows.
- [x] Wireframes should illustrate content discoverability (*e.g.,* search, navigation sidebar).

### Tasks

- [x] Create wireframe image for documentation landing page. Image should highlight basic components (*e.g.,* navigation panel, content pane) and content sources (*e.g.,* Markdown files sorted on metadata).
- [x] Create wireframe image for a sample pattern (*e.g.,* `azure-simple`). Image should highlight basic components (*e.g.,* navigation panel, content pane, search) and content sources (*e.g.,* Markdown files sorted on metadata).
- [x] Create wireframe image for sample project-wide documentation (*e.g.,* design principles). Image should highlight basic components (*e.g.,* navigation panel, content pane, search) and content sources (*e.g.,* Markdown files sorted on metadata).
- [x] Create wireframe image for interactive solution discovery (i.e., "choose-your-own-adventure") pages. Image should highlight basic components (*e.g.,* navigation panel, content pane, search) and content sources (*e.g.,* Markdown files sorted on metadata).
