### ISSUE TITLE
[Testing] Implement integration test capabilities for Test Framework component

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#109]
### Description
*As a template maintainer, I'd like to have a framework that I can use to simplify writing integration tests in order to reduce the friction to writing robust tests for my templates.*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Test framework should be augmented to support integration tests. The patterns to follow are shown in [Story #90](https://github.com/microsoft/cobalt/issues/90)
- [x] `azure-simple-hw` integration test is updated to use the new harness
- [x] `README.md` in test harness is updated to include references and examples of the integ test functionality.
- [x] Demo showing how to write an integ test is produced

### Resources
N/A

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by nmiodice** [comment]
From #90 
Pattern for integration test implementation

```go
// Something like this can be used to hold a reference to:
//    - Go Test
//    - Terraform Options
//    - List of user-defined functions that can be run to validate the deployment
//    - etc...
type IntegrationTestFixture struct {
	GoTest                *testing.T         // Go test harness
	TfOptions             *terraform.Options // Terraform options
        ...
}

// Something like this can be used to manage the terraform and test lifecycle
func RunIntegrationTests(fixture *IntegrationTestFixture ) {
}
```

Clients can use this using code similar to:
```go
func TestFoo(t *testing.T) {
	test_fixture := infratests.IntegrationTestFixture{
		GoTest:                t,
		TfOptions:             buildTerraformOptions(),
                ...
	}

	infratests.RunIntegrationTests(&test_fixture)
}
```

**Comment by nmiodice** [comment]
PR: https://github.com/microsoft/cobalt/pull/129
