### ISSUE TITLE
[Testing] Migrate test harness to its own git repo

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#110]
### Description
*As a developer, I'd like to leverage the test framework from projects other than Cobalt so that I can simplify infrastructure testing in other projects like Bedrock and <Your Cool Project Here>*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Test framework has a name, $NAME
- [ ] Test framework is moved to a github repo called $NAME
- [ ] Test image base is updated to not copy the ./test-harness folder into the base test image
- [ ] Any tests that leverage the test framework need to be updated to pull in the test harness from the new repo

### Resources
N/A

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by nmiodice** [comment]
Blocked on https://github.com/microsoft/cobalt/pull/129

**Comment by nmiodice** [comment]
We decided to punt this until later as the test harness may need to change to support CLI integration.
