### ISSUE TITLE
Documentation Site Technical Design

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#113]
### Description
*As a workstream lead, I've gained consensus on the gameplan and technical architecture for a fully operationalized documentation site. 

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should provide a devops flow diagram for the continuous integration pipeline.
- [ ] Should provide a devops flow diagram for the continuous deployment pipeline.
- [ ] Should provide both component and interface diagrams for all custom code artifact components. 
- [ ] Should provide a azure resource diagram for hosting a fully operationalized and highly available documentation site.

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
