### ISSUE TITLE
New TF Module: Azure Keyvault Certificate 

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#115]
### Description
*As a developer, I'd like to automate the creation of an RSA x509 SSL certificate and populate in keyvault. 

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should support creating a self signed RSA 2048 private key and push in KV for development purposes.
- [ ] Should support importing an existing x509 pfx private key and push in KV for QA, Pre-Prod and Prod purposes. 
- [ ] This module should be integrated with the app gateway module so SSL termination is enabled for all inbound traffic. 

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
