### ISSUE TITLE
Migrate to Terraform 12

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#118]
### Description
*As a developer, I'd like to migrate to terraform version 12 so I can leverage dynamic resource blocks and support registering a collection of app service endpoints to a target app gateway instance. 

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [X] Terraform 12 is used across all modules except `backend-state-setup`
- [X] Story written for TF 12 upgrade for `backend-state-setup`
  - https://github.com/microsoft/cobalt/issues/173
- [x] All unit/integration tests pass

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks

- [x] Upgrade `*.tf` files to TF 12 syntax
- [x] Upgrade environment variables to reflect TF 12 usage
- [x] Validate `azure-simple-hw` tests pass
- [x] Validate `azure-simple` tests pass
- [x] Update test harness + tests to work with TF 12 (note: terraform plan structure has massively changed)

**Comment by nmiodice** [comment]
Note: upgrade of backend state module should be done *after* https://github.com/microsoft/bedrock/pull/463 is merged. This PR is blocking the upgrade to TF 12 for the backend state module
