### ISSUE TITLE
Transition to Golang modules

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#119]
*As a developer, I'd like to migrate all golang package dependencies from `dep` -> go `mod`

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Local test harness using Docker should leverage `go mod` and not `dep`
- [x] Local test harness not using Docker should leverage `go mod` and not `dep`
- [x] Existing tests should pass

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
