### ISSUE TITLE
Refactor azure-simple-hw

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#120]
### Description
*As a developer, I want the `azure-simple-hw` template to use our existing terraform modules

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Main.tf references custom built App Service Module.
- [x]  Main.tf references custom built App Service Plan Module.
- [x]  Modules referenced in Main.tf are present in the generated terraform plan for the `azure-simple-hw` template.
- [ ]  Unit and Integration test remain functional.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
 - Pull Terraform Resources into modules
 - Update hello world test-harness
 - Cycle through hello-world local deployments to validate working deployment.
-  Submit PR
- Address comments
