### ISSUE TITLE
Task breakdown for Terraform 12 upgrade

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#139]
### Description
*As a cobalt/bedrock developer, I'd like to to understand the work required to upgrade Cobalt/Bedrock to Terrafform 12  so that I can effectively plan resources on my team*

### Acceptance Criteria
- [x] A task breakdown exists that covers all pending work for the TF 12 upgrade across both Bedrock and Cobalt projects.
- [x] Any dependencies between tasks are called out within the task description itself

Also, here are a few points that need to be addressed:

1. Work should be split across both teams
1. Need sign-off from Tim Park and James Nance 

### Resources
N/A

### Tasks
- [x] Research terraform 11/12 compatibility
  - Done
- [x] Research/document (as user stories) terraform 12 upgrade impact to Cobalt
  - Covered in https://github.com/microsoft/cobalt/issues/118
- [x] Research/document (as user stories) terraform 12 upgrade impact to Test Harness
  - Covered in https://github.com/microsoft/cobalt/issues/118
- [x] Research/document (as user stories) terraform 12 upgrade impact to Bedrock
  - No impact to Bedrock

**Comment by nmiodice** [comment]
Notes from meeting with James Spring and James Nance

- Timeline is likely a few weeks out for both teams
- Are Terraform core libraries being used to inspect Terraform Plan in Bedrock? -- Need to follow up with Nate Rose
- Need to deep dive on the possibility of a TF 0.12 module depending on a TF 0.11 module. This will inform the roll-out plan for TF 0.12 roll out

**Comment by nmiodice** [comment]
Challenges identified upgrading to Terraform 0.12

**Terraform plan structure + impact to Testing Harness (1)**
Terraform plan now displays changes as complex types. For example, suppose you had a *resource* `FOO` with an *attribute* `BAR` with the following *value* 
```shell
{ "a" : { "b" : ["c", "d"] } }
```
In Terraform 0.11 this will be represented in the plan like so:
```shell
"FOO.BAR.a.b.#" = 2
"FOO.BAR.a.b.0" = "c"
"FOO.BAR.a.b.1" = "d"
```

In Terraform 0.12 this will be represented in the plan like so:
```
FOO.BAR = { "a" : { "b" : ["c", "d"] } }
```

This means that when we assert over terraform plans (and **possibly output**) that we need to understand how to do complex type mappings, and also to figure out a meaningful way to do equality matches for the subset of the attributes that a client of the Test Harness supplies.

For example, if the client only cares about specifying that "c" is in the list above, how will they do that? How will we implement this?

**Comment by nmiodice** [comment]
Child stories for TF 12 upgrade
 - Upgrade most modules + test harness to TF 12: https://github.com/microsoft/cobalt/issues/118
 - Upgrade `backend-state` module to TF 12: https://github.com/microsoft/cobalt/issues/173
