### ISSUE TITLE
Document security implications of storing SSL keys in terraform plan/state files

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#140]
### Description
*As an admin/template maintainer/security guru, I'd like to have good documentation on where SSL secrets and other secrets are stored (e.g. terraform plan file locally, terraform state file on remote backend) so that I can configure my environment securely*

### Acceptance Criteria
- [ ] A deep dive is done to see where un-encrypted secrets may end up when using terraform
- [ ] All files/command outputs where sensitive information is stored should be documented.
- [ ] Best practices outlined for maintaining the integrity of the secrets are also documented

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
