### ISSUE TITLE
Service Principal Terraform Module

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#152]
### Description
*As a technical operator, I'd like to auto provision a service principal in a convention that supports azure role assignments for a configured target resource. 

A typical enterprise deployment will grant a service principal with access to a restricted set of resources which will be used by app dev teams. The access role(s) assigned to the SP scoped resources will depend on the various actions that an app dev team will expect to carry out. 

```script
$ az ad sp create-for-rbac --role Contributor --scopes /subscriptions/1234bca0-abcd-44bd-7da2-4bb1e9fa9876/resourceGroups/cobaltrg1
{
  "appId": "d35a60f3-d6fd-4308-63ee-40e936d29af4",
  "displayName": "azure-cli-2019-04-12-00-34-11",
  "name": "http://azure-cli-2019-04-12-00-34-11"
}
```

### Acceptance Criteria
- [x] Should auto generate an rbac service principal and application.  
- [x] Should support role assignments for a designated scoped resource object.
- [ ] Should verify that I can use this new terraform module to generate a new SP and authenticate to a target ACR registry following the `acrpush` role assignment. 

### Tasks
These tasks are subject to change pending the first item (Research)

- [x] Research creating a terraform module (ianphil - 1st TF)
- [x] Research existing SP TF modules
- [x] Create TF Module for SP
- [x] Add ability to set role
- [x] Add ability to set scope
- [x] Setup output with needed information
- [x] test migration to TF 12
- [x] Readme doc
