### ISSUE TITLE
Container / Image scanning

### ISSUE THREAD

**Issue by James-Nance** [microsoft/cobalt#164]
### Description
*As an operator, I'd like containers and images to be scanned for basic security compliance as part of CI/CD pipeline*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Containers are automatically scanned as part of CI/CD
- [ ] Scanning detects credentials and stops integration/deployment
- [ ] Scanning alerts when credentials are detected

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by James-Nance** [comment]
This will be handled in the docker build flow by Helium
