### ISSUE TITLE
Story deck

### ISSUE THREAD

**Issue by James-Nance** [microsoft/cobalt#166]
*As a stakeholder, I can view presentation materials that explain the goals, and architecture of Cobalt so that partners and customers quickly understand how to engage with the project*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Materials can be presented in less than 10 minutes
- [ ] Materials present how app devs can make use of Cobalt
- [ ] Materials show workflow with roles and responsibilities in deployment

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
