### ISSUE TITLE
Terraform Storage Account Module

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#169]
### Description
As a technical operator, I'd like to deploy a storage container with custom defined access roles. System identity should be able to access the container without using a storage key.

### Acceptance Criteria
- [x] Automate the creation of a storage account and storage container.
- [x] Assign roles to the storage container.
- [x] Create a managed identity (MSI) from the storage container.
- [x] Export the principal id's of MSI and id of the storage container.

Also, here are a few points that need to be addressed:
1. Move to Terraform 12 and PR comments have reopened a conversation about implementing a storage account module that supports multi-container deployment.

### Tasks
- Decide on default configurations for both the storage account and storage container.
- Decide if scalar module (count vs a single instance module).
- Create Readme.md
- Re-discuss if storage account module supports single container or multi-container.
