### ISSUE TITLE
Implement "subscription 1" components of isolated service template

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#188]
### Description
*As an enterprise customer I'd like to deploy an app service into an ASE so that I can verify that I am running in a secure VNET*

### Acceptance Criteria
- [x] 2 app services should be deployed to an ASE instance (with unit/integ tests). These should be deployed to a new resource group + service plan
- [x] The app service should be enabled for CD. However, as we won't be creating an ACR we don't need to configure the CD webhooks
- [x] An app insights instance should be deployed alongside the app service (with unit/integ tests)

### Resources
 - Technical Design: https://github.com/microsoft/cobalt/blob/master/infra/templates/az-isolated-service-single-region/docs/design.md

### Tasks
 - [x] Create VNET for testing. The VNET
 - [x] Create ASE for testing. The ASE + VNET should have an outwardly accessible port that enables testing
 - [x] Implement template by composing existing modules
 - [x] Implement unit tests for template
 - [x] Implement integration tests for template
 - [x] PR
 - [ ] Demo
