### ISSUE TITLE
Implementation: Key Vault (w/ VNET) integration for ASE template

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#195]
### Description
*As a user of the `az-isolated-service-single-region` template, I'd like to leverage key vault integration in order to store secrets for my application.*

### Acceptance Criteria
- [x] Key Vault integration to `az-isolated-service-single-region` should be achieved. This is intended to be deployed into the `app dev` subscription, so the azure provider used to create the module should be configured to use that subscription.
- [x] There should be VNET isolation configured for the Key Vault instance
- [x] ~~Create backlog item for a better testing strategy for VNET isolated resources~~ Plan has been identified: write extensions for Terratest to inspect resources using the Azure API.

### Resources
Here is the technical design for this template. https://github.com/microsoft/cobalt/blob/master/infra/templates/az-isolated-service-single-region/docs/design.md

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
