### ISSUE TITLE
Implementation: ACR integration (including initial image build/pushes) for ASE template

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#196]
### Description
*As a user of the `az-isolated-service-single-region` template, I'd like a new ACR to be created and my web apps to have CD integrated with this ACR in order to more easily deploy to my applications.*

### Acceptance Criteria
- [x] ACR integration to `az-isolated-service-single-region` should be achieved. This is intended to be deployed into the `app dev` subscription, so the azure provider used to create the module should be configured to use that subscription.
- [x] The `app_service_name` variable should be renamed and refactored to include metadata required to configure CD for the app service. This should be a list of metadata blobs where each blob specifies things like (just examples, define correct schema during implementation) (1) Git repo to trigger initial build, (2) path to docker file, (3) image name, (4) image tag, etc...
- [x] The initial apply (*only the initial apply*) of the terraform template should trigger the images to be built and pushed to the ACR via ACR build tasks
- [x] There should be VNET isolation configured for the ACR. This will need to be done *after* the build task completes
- [x] There should be a webhook set up for each image built. This should trigger a deployment to the app service whenever an image is pushed to ACR.
- [x] The changes should be tested with unit and integration tests

### Resources
Here is the technical design for this template. https://github.com/microsoft/cobalt/blob/master/infra/templates/az-isolated-service-single-region/docs/design.md

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
