### ISSUE TITLE
Design Integration Test Authentication Strategy

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#197]
### Description
As engineers, We want to understand how Auth will be added to integration tests, so that we can properly implement it in the test harness.

### Acceptance Criteria
- [ ] Should detail what the problem is
- [ ] Should include items that are out of scope
- [ ] Should include a visual diagram to help explain the work needed to be completed
- [ ] Should contain inputs and outputs
- [ ] Should contain any recommended implementation details like libraries, etc...
- [ ] Should contain information for using the secret in AzDO pipeline

### Resources
[Example of Test](https://github.com/microsoft/cobalt/blob/2cccc797672e389ad01360480415587efa92cf7f/infra/templates/az-service-single-region/tests/integration/template_integ_test.go#L69-L84)
[Example of AzDO](https://github.com/microsoft/cobalt/blob/2cccc797672e389ad01360480415587efa92cf7f/devops/providers/azure-devops/templates/azure-pipelines.yml#L96)
[AutoRest/Auth](https://docs.microsoft.com/en-us/go/azure/azure-sdk-go-authorization)

### Tasks
1. Detail problem
2. Provide background
3. Sample lib code
4. How to provide the function to test creators
5. Func input/outputs
6. Azure Devops Sec storage
7. Azure DevOps hand off of secret to test container
8. out-of-scope
9. Visual diagram
