### ISSUE TITLE
Implementation: HTTPS for ASE template

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#199]
### Description
*As an organization I'd like to support HTTPS so that I am not as vulnerable to a malicious attacker and/or network traffic snooping*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Certificate management strategy is defined with the customer
- [ ] ASE template supports certificates
- [ ] ASE template tests updated to use and verify HTTPS

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
