### ISSUE TITLE
[ ASE ] Design: Delete locks on Azure Resources to prevent outages

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#208]
### Description
*As a template deployment operator I want to define a technical strategy to prevent accidental resource deletion so that I can build templates in a way that are robust and will not fail from accidental deletes*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Design a resource lock strategy that will prevent resources from being deleted during a deployment
- [ ] Define and document guidance for how to actually delete resources (i.e., multiphase deployment or manual deletion or whatever you find to be the most robust strategy)
- [ ] Update https://github.com/microsoft/cobalt/issues/216 to reflect implementation tasks

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
