### ISSUE TITLE
Enable ARM_PROVIDER_STRICT flag to all deployments to prevent accidental deletes

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#213]
### Description
*As a template maintainer/deployment operator, I'd like to avoid accidentally importing resources into terraform in order to reduce the likelihood of an accidental delete*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] `ARM_PROVIDER_STRICT` is set to true for CI/CD pipeline in AZDO
- [ ] `ARM_PROVIDER_STRICT` is set to true for local testing
- [ ] `ARM_PROVIDER_STRICT` is set to true for all `.env.template` files

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by iphilpot** [comment]
This needs to be fixed for the single region template
