### ISSUE TITLE
[ ASE ] Integrate storage container module + VNET integration

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#219]
### Description
*As an app dev I'd like to leverage a VNET integrated storage account so that I can store unstructured data in a blob container*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] existing storage account module should be integrated to ASE template
- [ ] VNET integration should be added to storage container
- [ ] Integration tests validate VNET isolation for the storage account. Consider extending the terratest extensions.

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
