### ISSUE TITLE
[ ASE ] Service Principal Creation with RBAC roles

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#221]
### Description
*As a developer I'd like to have a service principal provisioned with RBAC access to my resources so that I can use them*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Service principal generated and reference-able from keyvault
- [ ] Service principal grants contributor access to KeyVault
- [ ] Service principal grants contributor access to ACR
- [ ] Service principal grants contributor access to Storage Account
- [ ] Service principal grants contributor access to SQL Server

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
