### ISSUE TITLE
[ Testing ] Refactor test harness, integrate automated testing to customer CI/CD pipeline

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#225]
### Description
*As a customer of Cobalt, I'd like to enable automated testing in my CI/CD in order to have more validation that changes in the template do not break deployments*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Automated tests should run in CI/CD pipelines for customer facing pipelines. Resources should be durable.
- [x] Automated tests should run in Cobalt CI pipeline. Resources should be durable.

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
- [x] Remove orchestration from test harness
- [x] Add unit/integration tests to client pipeline
- [x] Add unit/integration tests to cobalt pipeline
- [x] Leverage templates to orchestrate deployments using a common set of templates
- [x] Migrate diff detection logic into pipeline so that releases are optionally skipped if no changes happened
- [x] Add TF/Go lint checks to both pipelines
- [x] Validate cobalt pipeline
- [x] Validate customer pipeline
- [x] Remove template specific variables from templates
