### ISSUE TITLE
[Doc] az-hello-world template needs documentation (prev. azure-simple-hw)

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#227]
### Description
As a user, I'd like for the az-hello-world template to come with basic documentation that can be reliably used upon for becoming familiar with Cobalt.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Architecture diagram included
- [x] Description of prerequisites needed to begin using the template
- [x] Description of Use-Case
- [x] List of resources provisioned by the template
- [x] Description of intended audience

### Resources
*Document Reference*
https://github.com/microsoft/cobalt/blob/master/infra/templates/az-service-single-region/README.md

### Tasks
1. Pull latest repo
2. Update documentation for az-hello-world template
