### ISSUE TITLE
New Azure Developer Subscription

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#231]
### Description
As a developer, I want a subscription with a blank tenant, so that I can test AzDO pipelines that create service principles

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should be approved by the leadership
- [ ] Should have a blank tenant or use CSEWhite
- [ ] Service principle should be able to create service principles
- [ ] Github PR pipeline should move into this subscription
- [ ] Local dev .env file should be configured here
- [ ] backend state should be configured in this subscription

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
