### ISSUE TITLE
[ ASE ] Support IP whitelist for VNET integrated resources

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#232]
### Description
*As an enterprise customer, I want to enable access to VNET integrated resources based on an IP whitelist so that I can access resources from within my express route connected network*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] `az-isolated-service-single-region` accepts a new variable that defines a white-list of IPs to allow for the deployment. This should default to the empty list, `[]`
- [x] `container-registry` module accepts IP whitelist from `az-isolated-service-single-region` template
- [x] `keyvault` module accepts IP whitelist from `az-isolated-service-single-region` template
- [x] IP whitelist for keyvault + ACR validated by integration tests

Also, here are a few points that need to be addressed:

1. IP whitelist may be a mix of IPs and CIDR notation IP ranges

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by nmiodice** [comment]
KeyVault ACLs support IP address OR CIDR. Yay!
https://www.terraform.io/docs/providers/azurerm/r/key_vault.html#ip_rules

**Comment by nmiodice** [comment]
ACR supports CIDR block according to docs. Possibly IP address as well, based on portal.

https://www.terraform.io/docs/providers/azurerm/r/container_registry.html#network_rule_set
