### ISSUE TITLE
[Doc] Zero-to-CI/CD Documentation

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#237]
### Description
As a user, I'd like to have install documentation, in order to start from nothing and get up and running.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] New Quick start guide or the likes that will get you running deployments of hello world template using Azure DevOps
- [ ] Should have an Azure repo, with only the hello world template, and CICD configured using AzDO

Also, here are a few points that need to be addressed:

- [ ] Should start with a "blank" local dev environment
- [ ] Should start with a "blank" subscription
- [ ] Should start with a "blank" AzDO

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
