### ISSUE TITLE
[Doc] Fork-n-go Process

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#238]
### Description
*As a user, I'd like to have documentation, in order to understand how to release infrastructure using Cobalt.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should start with a Master repo containing one template
- [x] Should fork and deploy for a new app
- [ ] Should release a change and merge into forks

### Tasks
- [x] Create HDL repo to use latest terraform template
- [x] Create pipeline to use latest AzDO template
- [x] Identify gaps by attempting to fork repo + configure pipeline

*Pipeline Configuration Discovery*
- [ ] Refactor so that there are separate docs for the below points. Each section should contain a description of what is being documented so that people can quickly identify if its relevant for them.
  - [ ] Index with context for each of the below
  - [ ] ~~Getting started as an Advocated Pattern Dev~~ OUT OF SCOPE
  - [ ] ~~Getting started as an Advocated Pattern Owner~~ IN SCOPE FOR https://github.com/microsoft/cobalt/issues/239
  - [ ] Getting started as an Advocated Pattern "Fork N Go" Customer
  - [ ] Design motivation (this is existing documentation that we can move)

*Pipeline Configuration*
- [ ] Refactor so that there are separate docs for the below points. Each section should contain a description of what is being documented so that people can quickly identify if its relevant for them.
  - [ ] Index with context for each of the below
  - [ ] ~~Getting started as an Advocated Pattern Owner~~ IN SCOPE FOR https://github.com/microsoft/cobalt/issues/239
    - [ ] ~~Create master pipeline~~ IN SCOPE FOR https://github.com/microsoft/cobalt/issues/239
    - [ ] ~~Create master repository~~ IN SCOPE FOR https://github.com/microsoft/cobalt/issues/239
  - [ ] Getting started as an Advocated Pattern "Fork N Go" Customer
    - [ ] UI approach
    - [ ] CLI approach
  - [ ] Design motivation (this is existing documentation that we can move)

*Defining Strategy*
- [ ] ~~Identify if we should use GitHub app or PAT service connection~~ IN SCOPE FOR https://github.com/microsoft/cobalt/issues/240

*Pending Action Items*
- [ ] Leverage pipeline name for variable groups
- [ ] Make change + validate release works as expected + document any undocumented steps
