### ISSUE TITLE
Fix ip whitelist for azure devops

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#242]
### Description
As a user, I'd like to deploy an ASE isolated infrastructure that can generate secrets for key vault access upon deployment based on an ip whitelist.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Pending

Also, here are a few points that need to be addressed:

1. Pending

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by ThePhen** [comment]
@tasdevani21 and I have begun work. Here's out plan:

- [ ] Isolate our work from this repo and it's CI/CD pipeline
- [ ] branch onto `bugfix/242` and make some edits to isolate any AZ resources we'll create/destroy
- [ ] create an ADO project/repo/pipeline to isolate out pipelines & how they use self-hosted agents
- [ ] create a VM with self-hosted Linux build agent & add them to our ADO proj/pipeline
- [ ] ignore the HW and SR templates, for now, and get a clean baseline running of the ISO template

That gives us a starting point, and a clean-room to work in. Next:
- [ ] un-comment `whitelist`-related tests and [here](https://github.com/microsoft/cobalt/blob/master/infra/templates/az-isolated-service-single-region/app.tf) and [here](https://github.com/microsoft/cobalt/blob/master/infra/templates/az-isolated-service-single-region/tests/integration/integration_test.go)
- [ ] run the pipeline and see what fails
- [ ] share, scope & estimate what seems to be needed to fix any problems
- [ ] either pursue the fixes, or create new issues for this.

_More to follow_

**Comment by nmiodice** [comment]
>  create an ADO project/repo/pipeline to isolate out pipelines & how they use self-hosted agents

Question about this -- Are you planning to migrate the work back into the current AzDO project? If not, can we?

**Comment by ThePhen** [comment]
@nmiodice  Yes... we'll move it back. Since this item involves changes to the CI/CD settings (the AGENT_POOL), it isn't ideal to manipulate the 'shared/known good' CI/CD loop that keeps master protected.

Also, I've always preferred working (and that my team members) work in isolation, so that they do not create side-effects on each other. The AZ DevOps CLI instructions gave me enough of a push to effortlessly create our own ADO environment for this work, so that's where we're at.

**Comment by ThePhen** [comment]
Yesterday, @tasdevani21 and I hit a few snags that blocked us. We dove into the problems, but in the end, we simply ran the pipeline for this work again, and it started working.

At this point, we have a repeatable baseline that builds without the 'while-listing' features enabled. We're testing that this remains so, when using self-hosted build agents, this morning. With that settled, we'll enabled the 'white-listing' code, and start characterizing any problems/behavior.

**Comment by ThePhen** [comment]
While getting a 'clean room' host for the self-hosted linux build agent working, we've hit a few snags, due to needed dependencies. I suspect these are documented elsewhere (insluding in the recent build-agent Docker container work's Dockerfile). So far, I've instlaled `unzip`, `gcc`, `golang`, and `jq`.

**Comment by ThePhen** [comment]
Indeed... many things were needed. I took hints from this [Dockerfile](https://github.com/microsoft/cobalt/blob/master/devops/Build-Img/Dockerfile) to get things rolling.

**Comment by ThePhen** [comment]
Now, upgrading the build agent host to have more RAM. Bumping to 8GB vs 1GB.

**Comment by ThePhen** [comment]
@tasdevani21 and I have seen this work, now. (Well, we had to use SKIP_TEST to make it work.) I believe, at this point, we need to enable testing and get that working.

**Comment by ThePhen** [comment]
@tasdevani21 and I have completed the work, we've updated the tests, and we've merged in the latest updates to `origin/master`. At this point, we're running a few builds of these changes, and if there aren't any further problems, we'll open the PR soon.

Some things we've learned:

- The self-hosted build agents run most predictably when the host doesn't have GoLang or Terrafrom already installed. This allows the pipeline to install the indicated version (via env vars), however it is likely that installing these binaries will let the builds run more quickly (as the needed binaries won't need to be downloaded & installed with each build).
- The exsting code regarding whilelisted was good. The tests needed to be edited, however. Among the changes, we've removed the explicity checking of IP addresses within the lists of IP addresses that might get written to whitelist resources. Primarily, we've seen that the exact list of IP addresses chagnes, as the self-hosted agents come & go from various host VMs, which makes sense.
- Finally, we've been running our tests on a set of agents in an isolated AZ RG. With these changes, we can enable parallel, self-hosted builds for the over team workingon Cobalt. We'll continue to provide a pool of self-hosted agents, to support the team at-large, however it may be best to ultimately replace the agents we have today with 'official' agents hosted elsewhere. I've chatted a bit with @iphilpot about this. Today's agents are sufficient, and they let us keep moving forward.
