### ISSUE TITLE
Repeatably deploy hello-world template simultaneously 

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#251]
### Description
*As a user, I'd like to feel confident my deployment will succeed, when multiple people are deploying the same template.

### Acceptance Criteria
- [ ] Should focus on Hello-World template
- [ ] Should ensure all globally unique names are configurable
- [ ] Two deployments of the same template deployed at the same time succeed

### Resources
- [ ] Technical Design Document
- [ ] Documentation updates
- [ ] #247 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
