### ISSUE TITLE
Fix resource naming strategy used in templates

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/cobalt#254]
### Description
*As an app engineer, I'd like to have consistent and predictable resource identifiers (and FQDNs, where applicable), in order to have confidence that my deployment will succeed.*

### Issue Description
Cobalt's standard templates are not consistently using the same naming strategy for resources, and does not make it clear to a user of the template that they need to supply sufficiently unique identifier to avoid conflicts in resource names or FQDNs.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should consistently use combination of prefix+env when defining resource names (avoid referencing prefix or workspace directly)
- [x] Should consistently define template variables to be used for this purpose
- [x] Should update variables.tf file for each template to make clear the purpose of this var in the var's description
- [x] Should (optionally) allow insertion of a random character sequence into the resource name pattern
- Verify against #268 test plan

Also, here are a few points to be considered:

1. The HW template currently uses a "prefix" var for this purpose, while the others call the same var "name". These should be consistent from one template to another.
2. Suggestion for template variable naming: "uniqueName" (or similar) to make it clear that this establishes the **identity** of a deployment infrastructure
3. The HW template does not currently follow the same pattern used in the other templates where a local var is defined, and subsequent names are created from that base var
4. The terraform.workspace var is already a combination of prefix+environment, so beware of combining prefix+terraform.workspace

### Resources
- *Related to #247*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

- [x]  `TD` Go through all of the provider modules and move any name computations out into the calling template(s). Unsure which provider modules are affected at this time.

- [x] `KR` Refactor single service and hello world template to use locals block (also lift the locals out into a dedicated template file)
- [x] `KR` For each template, collect all of the resource name computations into the locals block (may not need to do anything for the single service templates).

- [x] `KR` Ensure that the base resource name and any parameter values used to compute the base name are consistent across templates
- [x] `KR` Come up with a naming pattern for the resources, and apply it to each template's locals computations.

- [x] `KR` Incorporate optional randomization element into resource name patterns. Should be configurable through template vars.

- [x] `TD` Update `variables.tf` with more accurate descriptions

- [x] `TD` Update any documentation with this pattern

- [x] `KR` Update unit/integration tests to remove reliance on hardcoded names (which will start breaking after this change)

- [x] `KR` Update FQDN generated names for app service endpoints

**Comment by KeithJRome** [comment]
Focus on ISO template
