### ISSUE TITLE
Document Known Limitations

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/cobalt#255]
### Description
*As a user, I'd like to be aware of the known limitations and targeted use cases of Cobalt before I choose to adopt it in my organization*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should highlight the current known limitations
- [ ] Should clearly state the appropriate target use cases (and call out any major inappropriate use cases, if possible)

A few points to be considered:

1. Limitations:
 * Resource Names are not validated until Apply phase (may leave a corrupt deployment on failure, see #249)
 * FQDNs are not verified until Apply phase (may leave a corrupt deployment on failure, see #249)
2. The intro/background should be refined to provide context for devs who are new to Cobalt
3. Identify common use cases targeted by Cobalt.
4. Identify use cases where Cobalt is *not* appropriate.

### Resources
 - [ ] *Main Cobalt README.MD*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
