### ISSUE TITLE
Updates to walkthrough documentation

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/cobalt#256]
### Description
*As a user, I'd like to have a more complete overview of the Getting Started walkthroughs prior to starting, and not be blocked from completing while partway through due to insufficient permissions or misunderstanding of input data values.*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should update the documentation for each walkthrough to identify the permissions needed to complete the task
- [ ] Should update the documentation for each walkthrough to include a preparation worksheet of data values (resource names, etc) that should be defined or obtained ahead of time
- [ ] Should update the documentation for each walkthrough to include callouts for each data value that needs to be captured for use later (and which cannot be known/defined ahead of time)
- [ ] Should update the documentation for each walkthrough to more clearly describe the role/scenario which it is intended to support
- [ ] Should update the documentation for each walkthrough to distinguish between those steps which need to be performed _once within an organization_, and those which need to be performed _for each deployment pipeline_

### Resources
- [ ] *Getting Started walkthrough for Cobalt Developer use case*
- [ ] *Getting Started walkthrough for Advocated Pattern Owner use case*
- [ ] *Getting Started walkthrough for Application Developer use case*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by ThePhen** [comment]
I've added an item to the list to indicate self-hosted agent requirements.

**Comment by TechnicallyWilliams** [comment]
I've added an item to the list to document places in the Azure portal where ui bugs incorrectly displays configurations. (Keyvault access policies requires refresh, App Reg Service Principals displays outdated reply_uri changes and requires tenant re-login)
