### ISSUE TITLE
Create technical overview documentation

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/cobalt#258]
### Description
*As an infrastructure architect evaluating Cobalt for my organization, I'd like to see more details about the underlying design of Cobalt, the patterns espoused within, and guidance on how to correctly introduce the Cobalt stack, in order to assess its suitability for my needs.*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should describe Cobalt's provider model, and the various intended customization/extensibility points
- [ ] Should illustrate the relationships between the primary components of the Cobalt stack (YAML Pipelines, Templates, Modules)
- [ ] Should fully document the role of YAML Pipelines in Cobalt, and any best practices regarding their usage
- [ ] Should fully document the template system in Cobalt, including the standard templates that ship with it (HW, Single-region, ISO) and creation of custom templates
- [ ] Should provide basic documentation coverage of the various terraform modules that ship with Cobalt to support templates

Also, here are a few points that should be considered:

1. This is probably a significantly large enough piece of technical documentation that it should be split into a new MD file under https://github.com/microsoft/cobalt/tree/master/design-reference/architecture and then referenced from the main README.MD document.
2. A good starting point for illustrating the Cobalt stack can be found in the Deployment Topology topic at https://github.com/microsoft/cobalt/blob/master/infra/templates/az-isolated-service-single-region/docs/design.md
3. Documentation of YAML Pipelines should include coverage of the standard/common pipeline variables used in Cobalt's YAML chain
4. The YAML Pipeline documentation should probably also discuss the example top-level pipeline definition that ships with Cobalt (`azure-pipelines.yml`)
5. **The role of the Terraform state container, and the need to have a shared container across all pipelines within an organization, needs to be highlighted. Without this, concurrent deployments are much more risky.**
6. Guidance for writing Unit/Integration Tests for custom templates and for more in-depth testing of deployed app environments should be included (possible overlap with #241)

### Resources
- *Main Cobalt README.MD*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
