### ISSUE TITLE
Build Version-n-go artifacts

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#264]
### Description
As a DevOps Engineer, I'd like to have all the artifacts for version-n-go, in order to easily deploy applications using the engineering repo.

### Acceptance Criteria
- [x] Should contain application.yaml file to configure CI/CD pipeline
- [x] Should contain application.tf file to deploy specific template
- [ ] All three templates deployable using this method

Also, here are a few points that need to be addressed:

1. Azure Hello World is the template for Development 

### Resources
[Technical Design Doc](https://github.com/microsoft/cobalt/blob/bf77a98549523f7adac5602e30af193c7e35c0db/design-reference/architecture/VersionAndGo/readme.md)

### Tasks

- [x] Verify terraforms version-n-go feasibility
- [x] Verify AzDo version-n-go feasibility
- [x] Resolve Git URL issues for GitHub and Azure DevOps Repos
- [x] Research strategy for handling Variable Groups across projects
- [x] Research and implement git credentials strategy
- [x] Create application.tf and test
- [x] Create application.yaml and test
- [ ] Create script to clone app pipeline DevOps objects
- [x] Determine how to share example application.tf / application.yaml files
