### ISSUE TITLE
Extract TF module to encapsulate generation of resource identifiers

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/cobalt#275]
### Description
*As a template developer, I'd like to have access to a component which manages resource names consistently and predictably, in order to streamline the development of new templates and customization of existing templates.*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should refactor the duplicated resource name generation code from the example templates (including randomized slugs in names and shortened names) into a shared terraform module
- [ ] Should document the various resource name patterns that are supported from this module
- [ ] Should export base resource names for use in other modules/templates

### Resources
- *Relates to work performed in Story #254*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
