### ISSUE TITLE
[ CICD ] Inline shell scripts to be single-task templates to simplify version 'n go process

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#298]
### Description
*As a consumer of Cobalt I don't want to have to check out the pipeline scripts explicitly. Instead, they should be inlined as yaml templates*

The current provided CI/CD pipeline templates have a dependency on external scripts defined in `devops/providers/azure-devops/templates/infrastructure/scripts`. For the version 'n' go process, we utilize the [Azure DevOps pipeline resources / repositories specification](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#repository-resource) in the `application.yml` so that the application's repository does not have to clone all of the advocated pattern repository, but rather need only point to the pipeline template within the referenced advocated pattern repository. Because our scripts are external, they are not available to the application pipeline. A workaround is to explicitly download them (currently implemented as an inline script [here](https://github.com/microsoft/cobalt/blob/66cb4c339b94e2307624c60e3407995e16537d9b/devops/providers/azure-devops/templates/infrastructure/azure-pipelines-app.yml#L18)), but if adjustments to the scripts are required and only available in the advocated patterns repository it is a more complex workaround to include the repository PAT in the git commands.

Instead, the inline scripts should be converted to YAML templates describing a step with inline script versus reference to an external `scriptPath`. In place of any task in our pipeline YAML where we refer to either a `Bash@3` or `AzureCLI@1` task with a `scriptPath`, we should instead point to the script-specific template.

For example, we could replace:
```yml
    - task: AzureCLI@1
      displayName: 'Create Terraform Execution Plan'
      inputs:
        azureSubscription: '$(SERVICE_CONNECTION_NAME)'
        scriptPath: './$(BUILD_ARTIFACT_NAME)/$(PIPELINE_ROOT_DIR)/$(SCRIPTS_DIR)/tf-generate-plan.sh'
        addSpnToEnvironment: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      env:
        TF_VAR_remote_state_container: $(REMOTE_STATE_CONTAINER)
        TF_VAR_remote_state_account: $(REMOTE_STATE_ACCOUNT)
``` 
with an external template instead of script:
```yml
    - template: tf-generate-plan.yml # Template reference
```
where `tf-generate-plan.yml` might look something like (*truncated example and not verified*):
```yml
steps:
  - task: AzureCLI@1
    displayName: 'Create Terraform Execution Plan'
    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      script: |
        export ARM_ACCESS_KEY=$(storageAccountPrimaryKey)
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_TENANT_ID=$(azureTenantId)
        
        TF_PLAN_FILE="${TF_WORKSPACE_NAME}_plan.out"
        
        terraform plan -out $TF_PLAN_FILE
    env:
      TF_VAR_remote_state_container: $(REMOTE_STATE_CONTAINER)
      TF_VAR_remote_state_account: $(REMOTE_STATE_ACCOUNT)
```

By converting to YAML templates, Azure DevOps will automatically pull them down from the repository reference without requiring any additional cloning or copying steps. This helps not only in removing a dependency on external scripts, but also makes scenarios where the source repository is private more streamlined.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should create and execute an Azure DevOps pipeline by referring to a repository resource without depending on external scripts
- [x] Should have all functionality currently scoped to a single script contained within a single YAML template representing that functionality

### Resources
See the Azure DevOps YAML schema for Repository resource: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#repository-resource

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
- [x] #314 Convert `lint-check-terraform.sh`
- [x] #318  Convert `lint-check-go.sh`
- [x] #323  Convert `set-cicd-flag.sh`
- [x] #326  Convert `test-integration.sh`
- [x] #331  Convert `test-unit.sh`
- [x] #334 Convert `tf-apply-plan.sh`
- [x] #334 Convert `tf-create-workspace.sh`
- [x] #334 Convert `tf-destroy.sh`
- [x] #334 Convert `tf-generate-plan.sh`
- [ ] Remove `commons.sh`
- [ ] Remove git clone task from `az-pipelines-app.yml`
