### ISSUE TITLE
Provide the Cobalt App-Dev community examples to help them get started

### ISSUE THREAD

**Issue by ThePhen** [microsoft/cobalt#308]
While helping myself and others to adopt Cobalt, I've felt a need to write an article, or series of articles, that lays out the journey from 'before Cobalt' to 'after Cobalt' for a few typical web apps and micro-service patterns.

Cobalt is under development, but I think it's at a point where such articles would be stable and help others to find their way forward with Cobalt.

### Description

As a Cobalt contributor, I'd like to craft what I've learned into some written stories that will help others to understand Cobalt, leverage Cobalt, and contribute to Cobalt.

### Acceptance Criteria

One, or more, articles that explain how to build contemporary applications whose infrastructure is managed via Cobalt. Such articles would either need to explain Cobalt, or describe how "advocated patterns," or "templates," are leveraged (preferably across a set of applications).

The stories need to be short enough to be appealing to read (quickly) and just detailed enough to provide a working relationship between the reader and Cobalt.

### Tasks

- [ ] enumerate existing usages of Cobalt, and derive story ideas from them.
- [ ] write some outlines / quick 'sketches' of some of usage patterns, then have the team of contributors and users provide feedback and direction (and writing assistance)
- [ ] write stories/articles!

Again, I'd like to keep these short, but valuable.

**Comment by ThePhen** [comment]
Closed as dupe of #85
