### ISSUE TITLE
CICD Error during deployment of single-region/hello-world: autorest/azure error during apply of autoscale

### ISSUE THREAD

**Issue by KeithJRome** [microsoft/cobalt#310]
### Description
*As a Cobalt developer, I'd like to see the example templates succeed during automated CI/CD deployment.*

During the latter stages of template deployment, some are failing with unusual error messages (see below). The same templates appear to deploy successfully from a local environment - the failures only occur during CI/CD on a build server.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] All three example templates (hello-world, single-service, iso) should deploy successfully during automated CI/CD

### Resources
- Error from deployment log: https://dev.azure.com/csedallascrew/project-cobalt/_build/results?buildId=1085&view=logs&j=1a08d14b-2493-53ec-cabc-8e3308a58870&t=180fd230-9725-5a7e-1138-c2f7f956801d&l=74
- Efforts to resolve this issue should be directed to WIP PR #303

### Tasks
- [x] Root Cause Analysis to understand the underlying reason for this deployment failure
- [x] Identify a resolution plan
- [x] Incorporate fix into PR working branch #303
