### ISSUE TITLE
Convert external Terraform shell scripts to YAML template with inline script

### ISSUE THREAD

**Issue by awkwardindustries** [microsoft/cobalt#334]
### Description
*As an advocated pattern owner, I'd like to execute these scripts as part of my build/release pipeline without requiring an external script file in order to allow application repositories to refer via reference without additional dependencies.*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should create `devops/providers/azure-devops/templates/infrastructure/scripts/tf-apply-plan.yml` with inline version of `tf-apply-plan.sh`
- [ ] Should create `devops/providers/azure-devops/templates/infrastructure/scripts/tf-create-workspace.yml` with inline version of `tf-create-workspace.sh`
- [ ] Should create `devops/providers/azure-devops/templates/infrastructure/scripts/tf-destroy.yml` with inline version of `tf-destroy.sh`
- [ ] Should create `devops/providers/azure-devops/templates/infrastructure/scripts/tf-generate-plan.yml` with inline version of `tf-generate-plan.sh`
- [ ] Should update `azure-pipeline-build-stage.yml` to utilize template reference to `tf-create-workspace.yml` instead of `tf-create-workspace.sh`
- [ ] Should update `azure-pipeline-build-stage.yml` to utilize template reference to `tf-generate-plan.yml` instead of `tf-generate-plan.sh`
- [ ] Should update `azure-pipeline-release-stage.yml` to utilize template reference to `tf-create-workspace.yml` instead of `tf-create-workspace.sh`
- [ ] Should update `azure-pipeline-release-stage.yml` to utilize template reference to `tf-apply-plan.yml` instead of `tf-apply-plan.sh`
- [ ] Should update `azure-pipeline-release-stage.yml` to utilize template reference to `tf-destroy.yml` instead of `tf-destroy.sh`

### Resources
Relates to #298 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
