### ISSUE TITLE
[EPIC] Documentation Rework

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#346]
As a user, I want documentation that walks me through using and customizing cobalt, so that I can get started and be productive to achieve more.

### Acceptance Criteria
- [ ] Deploy Hello World [stack] from local to Azure
- [ ] Compose elements into a [stack]
- [ ] Test your [stack] Unit/End-to-end
- [ ] Operationalize your [stack] HLD/Pipeline
- [ ] Customerize your [stack] for the app team
- [ ] Readme should reflect changes

Also, here are a few points that need to be addressed:

1. Should not use personas
1. Should feel like a lab
