### ISSUE TITLE
Quick Start Guide

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#348]
### Description
As a technical editor, I'd like to use existing docs to create a quick start guide, in order to allow any user to get started with cobalt.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should use content from the [Adpat Document](https://github.com/microsoft/cobalt/blob/master/docs/GETTING_STARTED_ADD_PAT_OWNER.md)
- [x] Should use content from the [Single Region Readme](https://github.com/microsoft/cobalt/tree/master/infra/templates/az-service-single-region)
- [x] Should "feel" like a lab not documentation.

Also, here are a few points that need to be addressed:

1. No persona / or the persona is Everyone.
2. See stub file for this story: docs/2_QUICK_START_GUIDE.md

### Resources
Epic #347 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by TechnicallyWilliams** [comment]
Quick start guide passively links to the az-hello-word CIT: #227 [Doc] az-hello-world template needs documentation (prev. azure-simple-hw)
