### ISSUE TITLE
Create a new template

### ISSUE THREAD

**Issue by ianphil** [microsoft/cobalt#349]
### Description
As a user, I'd like a document to describe how to create a new template for cobalt in order to deploy a specific infrastructure.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should pick up after the quick start guide
- [x] Should lead into testing the template
- [x] Should create a simple template with very few dependencies 
- [x] Should state where to put the template
- [x] Should state how to reference modules

Also, here are a few points that need to be addressed:

1. No update to repo README
2. No deployment via CI/CD
3. See stub file for this story: docs/3_NEW_STACK.md

### Resources
Epic #347 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
