### ISSUE TITLE
Template Testing

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#352]
### Description
As a user, I would like to understand how to test a template, so that I can insure changes do not cause regressions.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should test the template created in story #349 
- [ ] Should detail how and where to put the test
- [ ] Should explain how to run the test and debug
- [ ] Should explain how the test is run during CI/CD

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
Epic #346 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
