### ISSUE TITLE
Operationalize your template HLD/Pipeline

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#353]
### Description
As a user, I'd like to understand how to set up my template in my organization, in order to use and refine using my systems.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should explain how to move the template from the Cobalt repo into an HLD repo
- [ ] Should explain how to move the pipeline form the Cobalt repo inot an HLD repo
- [ ] Should explain how to create an HLD repo in Azure Devops
- [ ] Should explain how to setup a pipeline using the files from the HLD repo

Also, here are a few points that need to be addressed:

1. Does not cover version and go for app teams

### Resources
Epic #346 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
