### ISSUE TITLE
Customerize your template for the app team

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#354]
### Description
As a user, I'd like to understand how to share the template/pipeline with app teams so they can start deploying their infrastructure. 

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should explain the version and go process as a lab.
- [ ] Should contain the code for application.tf
- [ ] Should contain the code for application.yaml
- [ ] files should be located in the root of the app repo in an infra folder

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
Epic #346 

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
