### ISSUE TITLE
Troubleshoot and Debug Documentation

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#370]
### Description
As both a user or contributor, I'd like a centralized page that documents and highlights steps that I can take to troubleshoot and debug any issues that arise from using Cobalt.

### Acceptance Criteria
- [ ] Should be initialized with instructions for deleting .terraform sub-directory as a starting point for overcoming errors.
- [ ] The conclusion of each page in the walkthrough should provide a link to troubleshooting and debugging documentation.
- [ ] Page should invite others to contribute solutions to discovered problems.

### Tasks
**_Assignee should break down work into tasks here_**
- Create a new page in the docs directory
- Create an overview section to explain it's purpose
- Give page a table of contents with sub-section anchors
- Write instructions for deleting .terraform sub-directory
- Add contribution invitation
- Update all other walkthrough pages with a link back to this documentation
