### ISSUE TITLE
Port application CI/CD pipeline references into the project

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#372]
### Description
*As a Java Developer working on Azure, I'd like to consume a templetized CICD pipeline to enable stage deployments in a consistent way so that I can reduce the time it takes to deploy my application to Azure, and so that I can do it in a consistent way for each stage*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] The "Generic Service Pipeline" template for the project have been ported into the folder [here](https://github.com/microsoft/cobalt/tree/master/devops/providers/azure-devops/templates) under a subfolder called `app_service_maven` (or similar)
- [x] The "Azure Function Pipeline" template for the project have been ported into the folder [here](https://github.com/microsoft/cobalt/tree/master/devops/providers/azure-devops/templates) under a subfolder called `azure_function_docker` (or similar)
- [x] Existing documentation is also ported over

### Tasks
- [x] Port "Generic Service Pipeline" template into correct devops folder
- [x] Remove any proprietary data from "Generic Service Pipeline" template and documentation before commit
- [x] Remove service specific values from variable groups given as examples for the "Generic Service Pipeline"  Readme.
- [x] Port "Azure Function Pipeline" template into correct devops folder
- [x] Remove any proprietary data from "Azure Function Pipeline" template and documentation before commit
- [x] Remove service specific values from variable groups given as examples for the "Azure Function Pipeline"  Readme.
- [x] Templatize the "Azure Function Pipeline" for external repo consumption.

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
