### ISSUE TITLE
Migrate infrastructure testing library to a new repository

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#374]
### Description
*As a consumer of Terraform, I'd like an easy way to write tests against my terraform deployments so that I can validate that they are successful (or not)*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] The infrastructure testing code can be consumed without needing to consume all of Cobalt's other dependencies through its own repository
- [x] Changes to infrastructure testing from "the project" are ported back into this repo
- [x] Existing tests reference the new repo

### Tasks
- [x] Create new repository 
- [x] Copy files to new repo from "the project" 
- [x] Package Go module
- [x] Update test references to point to new repo

**Comment by AdanOrtiz** [comment]
PR is the new repo [here](https://github.com/microsoft/terratest-abstraction/pull/1 )
