### ISSUE TITLE
Port improved infrastructure CI/CD pipelines into project

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#375]
### Description
*As a developer that needs to deploy infrastructure into Azure DevOps, I want to leverage a robust CI/CD pipeline in order to deploy my infrastructure in a controlled manner*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] The project infrastructure pipelines replace the current infrastructure CICD pipelines
- [x] The variable groups in the Azure DevOps instance are updated to reflect the minimum set of variables that are required to run the pipelines
- [x] Any bugs or regressions are captured as backlog stories

### Tasks

- [x] Delete old pipelines
- [x] Copy new pipelines over
- [x] Test new pipelines on az-hello-world
- [x] Test new pipeline on az-microsvs template (not isolated)
- [x] Test new pipeline on ASE template
- [x] Test new pipeline with all 3 envs
- [x] Merge code
- [x] Delete old pipelines references & configure new branch policies
- [x] Verify docs up to date

**Comment by nmiodice** [comment]
Note; there may be another PR for other documentation updates impacted by this change.
