### ISSUE TITLE
As a developer, I want to auto trigger a release to QA for merged pull requests

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#57]
### Description
*As a developer, I want to auto trigger a release to QA for merged pull requests*
We want to deploy a source terraform build artifact to an azure QA environment when pull requests are merged to master. This will be represented as an azure devops release pipeline. The source artifact will comprise of the terraform template to deploy. The artifact deployed to QA should match what was tested and deployed to the integration environment. We should also run the integration tests after the artifact is applied in the QA env.

### Acceptance Criteria
- [ ] Should assert that there's a gated release candidate created targeting the QA stage following a PR merge.
- [ ] Should assert that the integration tests pass once the release candidate is approved.
- [ ] Should assert that you can manually access the app service website resource in QA. 
- [ ] Should assert that the `README` in the azure devops folder provides step-by-step instructions with setting up the release pipeline in azure devops including animated gifs. 

### Resources
*Mockups*
Include screenshots of a successful release in QA from azure devops. 

### Tasks
*Update the readme documentation in the azure devops folder.
*Setup release pipeline in azure devops
*Setup variable group sourced by keyvault to resolve secret variables like service principal credentials.
