### ISSUE TITLE
As a developer, I can configure and deploy Azure App Service

### ISSUE THREAD

**Issue by James-Nance** [microsoft/cobalt#60]
### Description
*As a developer, I can configure and deploy Azure App Service*

For Cobalt, App Service should provide:

- App/container hosting
- Public IP mapped to container port (Dependency on Julio Research)
- Load balancing (Another User story for scale out config)

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)

- [ ] Service plan is already deployed before starting deployment of app service
- [ ] Key value pair for app service name and linux fx version
- open question: service aplan module depends on app service
- [ ]Output in readme with an example output
- [ ] VNET is an option for App Service. (No data block needed)

- [ ] No hardcoded variables in module config; everything set through Terraform template
- [ ] Usage referenced in Azure Simple template
- [ ] Screenshot showing resource provisioned in Azure Portal

Also, here are a few points that need to be addressed:

1. No hardcoded variables in module config; everything set through Terraform template

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by code4clouds** [comment]
App Service requires App Service Environment (ASE) to be in the same vnet as the AppGateway (If we are to follow the Game Plan).

**Comment by code4clouds** [comment]
From the Game Plan diagram there is no public IP mapped on the App Service as the traffic is routed through the VNET as incoming from the App Gateway...    As in Traffic Manager-(public)->App Gateway-(vnet)->App Service.

**Comment by code4clouds** [comment]
Should the key/secrets for ACR be wired to the Azure Key Vault?

**Comment by James-Nance** [comment]
> Should the key/secrets for ACR be wired to the Azure Key Vault?

ACR and Key Vault would normally be managed by the dev / org, so not within scope of this (per the architecture diagram) infrastructure.  I'd say do what you need to do for testing purposes, but nothing should be hard-coded in the modules or templates.  Sorry if I'm misunderstanding the question.

**Comment by code4clouds** [comment]
Agree.  They are both managed by the org, but they still need to be "wired/configured" to the module or access by the template (#63 ) and sent down to this module.

**Comment by erikschlegel** [comment]
The deployment is happening as part of the test harness which sets the service principal credentials in the environment automatically. In summary, KV integration is already accounted for as you set this in your .env file.

Erik

________________________________
