### ISSUE TITLE
As a developer, I can configure and deploy an Azure Service Plan

### ISSUE THREAD

**Issue by James-Nance** [microsoft/cobalt#61]
### Description
*As a developer, I can configure and deploy an Azure Service Plan*

For Cobalt, Service Plan should define the resources to run a simple test app.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] No hardcoded variables in module config; everything set through Terraform template
- [ ] Usage referenced in Azure Simple template
- [ ] Screenshot showing resource provisioned in Azure Portal

Also, here are a few points that need to be addressed:

1. No hardcoded variables in module config; everything set through Terraform template

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
