### ISSUE TITLE
As a developer, I can configure and deploy Azure API Management service

### ISSUE THREAD

**Issue by James-Nance** [Microsoft/cobalt#62]
### Description
*As a developer, I can configure and deploy Azure API Management Service*

For Cobalt, the APIM service should provide:

- Reverse proxy for API calls
- Logging for API traffic
- SSL termination
- Service authentication via JWT toeks

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] No hardcoded variables in module config; everything set through Terraform template
- [ ] Usage referenced in Azure Simple template
- [ ] Screenshot showing resource provisioned in Azure Portal

Also, here are a few points that need to be addressed:

1. No hardcoded variables in module config; everything set through Terraform template

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by manojvazirani** [comment]
@James-Nance / @erikschlegel : I was able to deploy the api manager, but had questions for the other requirements mentioned in the story, because of my lack of experience with Azure API manager:
1. Reverse proxy for API calls - provided by API manager
2. Do we plan on using `Azure Event Hub` for Logging for API traffic or API manager provides this too?
3. SSL termination - Provided when API manager is in a VNET. Presumably azure-simple.
4. Service authentication via JWT tokens - I would think it should be [policy](https://www.terraform.io/docs/providers/azurerm/r/api_management.html#xml_content) but its for XML and not JSON. 

cc @code4clouds

**Comment by manojvazirani** [comment]
Also FYI, I have observed that the average time to deploy an API manager is > 20 minutes.
azurerm_api_management.apimgmt: Creation complete after 20m8s
