### ISSUE TITLE
As a developer, I can deploy Azure services to support a simple / single region infrastructure

### ISSUE THREAD

**Issue by James-Nance** [microsoft/cobalt#63]
### Description
*As a developer, I can deploy Azure services to support a simple / single region infrastructure*

This should incorporate a simple Terraform manifest that references:

Colbalt/App Gateway
Cobalt/App Service
Cobalt/Service Plan
Colbalt/API Management
Bedrock/Backend
Bedrock/Vnet [module](https://github.com/Microsoft/bedrock/blob/master/cluster/environments/azure-simple/main.tf#L10) - Will require two [subnets](https://user-images.githubusercontent.com/7635865/56060370-45a69500-5d2c-11e9-9c91-3a2809fa13da.png): 1. app gateway 2. APIM.
Bedrock/Traffic Manager [profile](https://github.com/Microsoft/bedrock/blob/933fb9cda5023de085367e72773ef133384bceb3/cluster/environments/azure-multiple-clusters/trafficmanager.tf#L7)
Bedrock/Traffic Manager Public Endpoint [module](https://github.com/Microsoft/bedrock/blob/d5939e09140d809331342725702c2681c409e901/cluster/environments/azure-multiple-clusters/aks-westus.tf#L66)

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)

- [x] VNET module referenced from Bedrock
- [x] Service Plan referenced
- [x] Find/Create a container that serves as REST endpoint
- [x] Web App Service referenced
- [ ] API Management referenced ( TODO: into WebApp )
- [ ] Traffic Manager referenced ( TODO: Research VNET vs PublicIP, check multi-cluster sample )
- [ ] Configuration via implementation of .env
- [ ] Provide the users with an IP Address to use in their browser
- [ ] Screenshot of Azure services running in Azure Portal
- [ ] test/reference "Hello World" web app is accessible
- [x] Add variables.tf with required environmental values

Also, here are a few points that need to be addressed:

1. Should use Terraform
1. Should contain any variables for Azure services

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
- [x] VNET module referenced from Bedrock
- [x] Service Plan referenced
- [x] Find/Create a container that serves as REST endpoint
- [x] Web App Service referenced
  - [ ] Add Access Restriction Rule-set for AppService allowing the API_Manager
- [x] API Management referenced ( TODO: into WebApp )
  - [ ] Add API Front actions to the API Manager 
- [x] App Gateway referenced
  - [ ] Wired App Gateway to APIM
- [x] Traffic Manager referenced ( TODO: Research VNET vs PublicIP, check multi-cluster sample )
  - [ ] Wired the TM to App Gateway
- [x] Configuration via implementation of .env 
- [ ] Provide the users with an IP Address to use in their browser
- [ ] Screenshot of Azure services running in Azure Portal
- [ ] test/reference "Hello World" web app is accessible
- [x] Add variables.tf with required environmental values

### Blockers
- [ ] Custom rules set must be added to the WebApp in the terraform module.
<img width="1455" alt="2019-05-08_10-46-23" src="https://user-images.githubusercontent.com/29647050/57390970-7cd16000-718b-11e9-8adc-041968b0e65a.png">
 
  - Acceptance criteria:
    - the rule must be done in Terraform
    - the rule must be added in the app service
    - the vnet/subnet to be used for the rukle should be an value that will be passed by the template to the module.

#

- [ ] API Manager needs a front end action to allow clients to connect to the webapp.
<img width="1469" alt="2019-05-08_10-45-27" src="https://user-images.githubusercontent.com/29647050/57391414-7e4f5800-718c-11e9-99f3-bd09ffd34519.png">

  - Acceptance criteria:
    - the action must be done in Terraform
    - the action must be part of the API module
    - the action should be a value set by a module variable and set by the template.

#

- [ ] App Gateway needs the private IP of the APIM added to the backend pool.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/29647050/57394507-b9a15500-7193-11e9-9180-cde9029cbcc1.png">

  - Acceptance criteria:
    - the IP should be added using Terraform
    - the back-end pool IP must be part of the App Gateway module
    - the backed IPs should be set by a module variable sent by the teamplate.

**Comment by code4clouds** [comment]
PublicIP is required for AppGateway?  Two option:
1.  Create a new module for public IPs and pass the ref to the AppGateway.
2. The AppGateway module creates the public IP internally and return it as an output.

**Comment by code4clouds** [comment]
There is no mentioned of Azure KeyVault... How is it going to be utilized in Azure-Simple?

**Comment by code4clouds** [comment]
I hit this issue: https://github.com/hashicorp/terraform/issues/8048 looking for a workaround.

**Comment by erikschlegel** [comment]
> I hit this issue: [hashicorp/terraform#8048](https://github.com/hashicorp/terraform/issues/8048) looking for a workaround.
@code4clouds what are you trying to do?

**Comment by code4clouds** [comment]
The bug is trying to get a module output of type list and consume it as a variable for the next module. 
eg. The AppService create a service urls for the apps created (output list) and these will then be passed as input (list) to the AppGateway/APIManager to be connected.  Like mentioned today the count fails on computed values due to this bug.

**Comment by erikschlegel** [comment]
> The bug is trying to get a module output of type list and consume it as a variable for the next module.
> eg. The AppService create a service urls for the apps created (output list) and these will then be passed as input (list) to the AppGateway/APIManager to be connected. Like mentioned today the count fails on computed values due to this bug.

Did this [workaround ](https://github.com/hashicorp/terraform/issues/8048#issuecomment-282847087)address the issue
