### ISSUE TITLE
[Testing] Test Framework Generalization

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#90]
**A good user story should be (I-N-V-E-S-T principle)**

* _Independent_ (from other user stories, allowing to realize them in any order);
* _Negotiable_ (omit details that would freeze the story);
* _Valuable_ (implementation delivers an increment of functionality, observable by and useful to users);
* _Estimable_ (developers should be able to estimate its size relative to other stories);
* _Sizable_ (implementation fits in one iteration – if it needs many to complete, it is an EPIC);
* _Testable_ (user must be able to check the conditions of satisfaction).

### Description
*As a developer, I'd like to leverage an testing framework in order to reuse automated test stages across terraform templates. Some of these stages comprise of terraform plan inspection, E2E app service connectivity assertions, Terraform template linting, etc.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Testing framework should still live in this repository, but should be designed in a way that is shareable between multiple repos/projects
- [x] Define and implement common patterns for  unit testing
- [x] Define but not necessarily implement common patterns for integration testing
- [x] Define and implement consistent lint checks for *.go files. If any *.go files do not pass linting, the build should fail
- [x] Define and implement consistent lint checks for *.tf files. If any *.tf files do not pass linting, the build should fail

### Tasks
- [x] Fail builds if *.go files do not pass lint checks
- [x] Fail builds if *.tf files do not pass lint checks
- [x] Define consistent testing patterns for unit testing TF modules/templates
- [x] Implement generic testing harness that simplifies writing unit tests for TF modules/templates
- [x] Define consistent testing patterns for integration testing TF modules/templates
- [x] Write story to implement generic testing harness that simplifies writing integration tests for TF modules/templates

**Comment by nmiodice** [comment]
Story for integ tests: https://github.com/microsoft/cobalt/issues/109

**Comment by nmiodice** [comment]
Story for moving harness to its own repo: https://github.com/microsoft/cobalt/issues/110

**Comment by nmiodice** [comment]
Pattern for integration test implementation

```
// Something like this can be used to hold a reference to:
//    - Go Test
//    - Terraform Options
//    - List of user-defined functions that can be run to validate the deployment
//    - etc...
type IntegrationTestFixture struct {
	GoTest                *testing.T         // Go test harness
	TfOptions             *terraform.Options // Terraform options
        ...
}

// Something like this can be used to manage the terraform and test lifecycle
func RunIntegrationTests(fixture *UnitTestFixture) {
}
```
