### ISSUE TITLE
CLI: Test Harness Configuration

### ISSUE THREAD

**Issue by iphilpot** [microsoft/cobalt#95]
**A good user story should be (I-N-V-E-S-T principle)**

* _Independent_ (from other user stories, allowing to realize them in any order);
* _Negotiable_ (omit details that would freeze the story);
* _Valuable_ (implementation delivers an increment of functionality, observable by and useful to users);
* _Estimable_ (developers should be able to estimate its size relative to other stories);
* _Sizable_ (implementation fits in one iteration – if it needs many to complete, it is an EPIC);
* _Testable_ (user must be able to check the conditions of satisfaction).

### Description
As a developer, I'd like to have a CLI that will configure my local test harness, so that I don't have a lot of manual effort.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Terraform variable and deployment files are auto-generated once the target template name is provided. 
- [ ] Pre-requisite dependencies are validated via the CLI.
- [ ] Artifacts required to run the test harness locally are pulled down via the CLI.

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
Command: Run - setup and test
 - bool flag: --docker
 - download test runner script to /tmp/cobalt-testrunner-{date/time}.sh
 - run script (expect script to verify latest ver for base image)
 - output stdout
 - clean up files
 - leave base image

**Comment by iphilpot** [comment]
This was moved to the Orion repo: https://github.com/microsoft/orion/pull/6
